### ISSUE TITLE
expected class-name before '{' token

### ISSUE THREAD

**Issue by rponweb** [mon/Arduino-USB-Rename#1]
In file included from C:\p***\2022\Arduino\usbRename\usbRename.ino:1:0:
C:\Users\Administrator\Documents\Arduino\libraries\Arduino-USB-Rename-master/usb_rename.h:3:45: error: expected class-name before '{' token
 class USBRename : public PluggableUSBModule {
                                             ^
C:\Users\Administrator\Documents\Arduino\libraries\Arduino-USB-Rename-master/usb_rename.h:10:23: error: 'USBSetup' has not been declared
     int getDescriptor(USBSetup& setup);
                       ^~~~~~~~
C:\Users\Administrator\Documents\Arduino\libraries\Arduino-USB-Rename-master/usb_rename.h:11:16: error: 'USBSetup' has not been declared
     bool setup(USBSetup& setup);
                ^~~~~~~~
exit status 1
Error compiling for board Arduino Uno.

**Comment by mon** [comment]
Sorry, but this library is for USB native arduinos such as the Leonardo. The uno is not compatible.
